name = "american-space-oujda"
compatibility_date = "2026-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npx @cloudflare/next-on-pages"

[vars]
NEXTAUTH_URL = "https://american-space-oujda.pages.dev"
